### ISSUE TITLE
Feature: AMOLED Theme

### ISSUE THREAD

**Issue by swedneck** [vadret/android#100]

**Comment by sphrak** [comment]
Thanks for your request.
I will not able to pursue this issue right now because of other work. I do accept pull requests though.

**Comment by sphrak** [comment]
@swedneck glad påsk, funkar detta tro? 

![Screenshot_20190421-202018_Vadret](https://user-images.githubusercontent.com/26309425/56474274-dccfc300-6477-11e9-9aba-83c4461e2e3f.png)
![Screenshot_20190421-202033_Vadret](https://user-images.githubusercontent.com/26309425/56474275-dd685980-6477-11e9-85e1-7f3d038dd319.png)
![Screenshot_20190421-202052_Vadret](https://user-images.githubusercontent.com/26309425/56474276-dd685980-6477-11e9-945e-6c9653d24999.png)

**Comment by swedneck** [comment]
Briljant!
Eller nej, mörka teman är ju faktiskt motsatsen till briljanta.. :D
