### ISSUE TITLE
Bug: "Feels like" temp is inconsistent in version 0.1.7

### ISSUE THREAD

**Issue by siwan05** [vadret/android#107]
When I refresh the data (by pulling down) I get different data each time for the same periods. See the three attachments, there I have refres
![screenshot_20190121-113746_vdret](https://user-images.githubusercontent.com/6042171/51469376-87e5b900-1d71-11e9-8f52-e536b0a78c54.jpg)
![screenshot_20190121-113739_vdret](https://user-images.githubusercontent.com/6042171/51469390-8c11d680-1d71-11e9-9d87-0fa3051948f6.jpg)
![screenshot_20190121-113732_vdret](https://user-images.githubusercontent.com/6042171/51469395-8f0cc700-1d71-11e9-9b8d-620b1e54dcb4.jpg)

hed three times in a row.

**Comment by sphrak** [comment]
@siwan05 
Thanks for reporting, that's odd, I can only reproduce this on sthlm. I will investigate.

**Comment by siwan05** [comment]
Awesome response time, big thanks!
