### ISSUE TITLE
Feature: Add date next to weekday

### ISSUE THREAD

**Issue by siwan05** [vadret/android#108]
I think it would be nice to have the date next to the weekday, especially when you have scrolled down a few days on the list.

**Comment by sphrak** [comment]
@siwan05 good idea, would you rather have 'Tuesday, tomorrow' or 'Tuesday, Jan 22nd' for example?

**Comment by sphrak** [comment]
Like this perhaps? if okay I can push 0.1.8 tonight already, ive fixed the other inconsistency issue

![image](https://user-images.githubusercontent.com/26309425/51492219-5e4c8200-1db1-11e9-8a39-f7fc9f03cb0b.png)
