### ISSUE TITLE
Wind direction arrow is reversed

### ISSUE THREAD

**Issue by creideiki** [vadret/android#190]
Using version 1.2.6 from F-droid.

The app currently shows this for my location:
![vadret-wind-direction](https://user-images.githubusercontent.com/1296902/70852815-1bead280-1ea6-11ea-8596-cbd53a491136.png)
Note that the description says "southeastern", but the icon shows a northwesterly wind direction.

METAR for the local airport, about 5km away, says 13004KT, which is southeasterly, so it seems the icon is reversed 180 degrees from what it should be.

**Comment by sphrak** [comment]
Hello @creideiki,
You are correct, it is indeed the wrong orientation. I have released a fix but probably takes a couple of days for it to propagate to F-droid since i'm not responsible for that distribution chain. The play store variant will be out in a couple of hours.

cheers
