### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [vadret/android#239]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by sphrak** [comment]
This would be nice to have, but given how tiny the user base currently is it doesn't warrant the effort for me right now. But if anyone wants to take a stab at this please go ahead.

**Comment by mondlicht-und-sterne** [comment]
that was just a hint, if this is not possible or too difficult or you don't have time, you can close the issue.
