### ISSUE TITLE
translation: add german translation

### ISSUE THREAD

**Issue by sphrak** [vadret/android#25]

**Comment by dieterpl** [comment]
I would like to do that for Hacktoberfest. I'm a German native speaker, can you assign me?

**Comment by sphrak** [comment]
@dieterpl sure im gonna figure out how to add you

**Comment by sphrak** [comment]
@dieterpl It seems I have to setup teams and stuff to even be able to assign you because this is a organisation and I dont have time to do that today. However you can still work on this.

**Comment by dieterpl** [comment]
I created a pull request: #26
