### ISSUE TITLE
suggestion: language selectable via settings

### ISSUE THREAD

**Issue by sphrak** [vadret/android#30]

**Comment by JanStoltman** [comment]
@sphrak How about just changing the language settings of a phone? Wouldn't it be enough?

**Comment by sphrak** [comment]
@JanStoltman Wouldn't that mean you change the entire language of the phone though? I myself for example run mine on english out of habit, but I'd prefer the forecasts in Swedish. Though I am not even sure if its possible, its just somehing I found myself wanting to do.

**Comment by JanStoltman** [comment]
@sphrak I'm on it

**Comment by sphrak** [comment]
@JanStoltman closing since this was not very viable
