### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by Rudloff** [vadret/android#86]
Hello,

When trying to build 0.1.2 with `./gradlew assemble`, I get the following error:
```
Execution failed for task ':app:processFdroidDebugManifest'.
> java.lang.NullPointerException (no error message)
```

Here is the full log: https://gist.github.com/Rudloff/c2ce9f9d83c06d20f8032eb4d18e1a94

I'm getting this error with any variant.
Do I need to add something to my `.env` file maybe?

**Comment by sphrak** [comment]
@Rudloff I believe this should work, could you if possible test this PR https://github.com/vadret/android/pull/87?

Clone:
```
git fetch origin
git checkout -b build/fixes-building-without-env-file origin/build/fixes-building-without-env-file
```

I also wonder if I should enable `signingConfig signingConfigs.release` on fdroid product flavor aswell? I am not sure if you can sign it otherwise, I am a bit new to this.

**Comment by Rudloff** [comment]
> I also wonder if I should enable signingConfig signingConfigs.release on fdroid product flavor aswell? I am not sure if you can sign it otherwise, I am a bit new to this.

F-Droid uses its own signing mechanism, separate from the build step. So the fdroid flavor does not need to have any signing config.

**Comment by sphrak** [comment]
fixed in https://github.com/vadret/android/pull/87
